export const conf = {
  NORMAL_STROKE: 1,
  SEQUENCEFLOW_STROKE: 1.5,
  ASSOCIATION_STROKE: 2,
  TASK_STROKE: 1,
  TASK_HIGHLIGHT_STROKE: 2,
  CALL_ACTIVITY_STROKE: 2,
  ENDEVENT_STROKE: 3,

  COMPLETED_COLOR: "#2632aa",
  TEXT_COLOR: "#373e48",
  CURRENT_COLOR: "#017501",
  HOVER_COLOR: "#666666",
  ACTIVITY_STROKE_COLOR: "#bbbbbb",
  ACTIVITY_FILL_COLOR: "#f9f9f9",
  MAIN_STROKE_COLOR: "#585858",

  TEXT_PADDING: 3,
  ARROW_WIDTH: 4,
  MARKER_WIDTH: 12,
}
